---
title: "Frequently Asked Questions (FAQs)"
output:
  html_document:
    toc: true
vignette: >
  %\VignetteIndexEntry{Frequently Asked Questions (FAQs)}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Installing `asar`

## How can I download the package?

Please consult [the README page](https://nmfs-ost.github.io/asar/index.html#installation) for installation instructions.

## Alternative instructions

If you are receiving the following error when trying to download the package:

```         
Using GitHub PAT from the git credential store.
Initiating curl with CURL_SSL_BACKEND: openssl
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 403.
  Resource protected by organization SAML enforcement. You must grant your OAuth token access to this organization.
```

If you're a member of the NMFS OST organization, you can [authorize your token](https://docs.github.com/en/enterprise-cloud@latest/authentication/authenticating-with-single-sign-on/authorizing-a-personal-access-token-for-use-with-single-sign-on) to solve this issue.

Otherwise, please download the package using this code:

```         
install.packages("asar", repos = c("https://nmfs-ost.r-universe.dev", "https://cloud.r-project.org"))
```

# Setting up the report skeleton

## `create_template()` isn't working. What do I do?

This could mean a lot of things. Most of the time, when `create_template()` is not working, it means you are missing a key argument to the function. Make sure to read the error message(s) clearly and check the 'report' folder where all of the file were created. If you have exhausted your options and double checked that you have all of the correct arguments, then please open an [issue](https://github.com/nmfs-ost/asar/issues).

## What should I do if I have a species complex/multispecies assessment?

`asar` was designed to create reports for single species. As a workaround, you can  combine multiple species using "and" in the `species` argument of `create_template()`. 
For example, the following code will produce a report with two species in the title, though a cover image must be added manually since cover images are matched to single species:

`create_template(species = "Species A and Species B")`

We encourage users writing species complex/multispecies assessments to remember that the reports are highly customizable both before and after the skeleton is created. For example, the `create_template()` command allows for customization by providing custom section options. After the skeleton has been created, advanced Quarto users can edit the YAML, chunk options, and other components of the report, and everyone can customize the report's text.

While we have striven to add sufficient options for customization, we highly discourage changing the formatting or adding many sections so that the final document does not stray far from the intended, standardized format.

# Editing reports

## What is the purpose of the R chunk labelled `output_and_quantities` in the skeleton?

This chunk is what we call the preamble. It loads in commonly-used estimates and quantities that you can reference throughout your report, making the document dynamic. By updating the values calculated in your report folder's [preamble.R script](https://github.com/nmfs-ost/asar/blob/d3070f349f12a49ad6e6ae10aa2865de104b5581/inst/resources/preamble.R#L4) file, you can easily update the values throughout your report.

## How do I reference one of the quantities in the preamble in my text?

To reference these quantities in your text, please use the following notation:

```{verbatim}
`r start_year`
```

For example, if `start_year` = 2025 and your report contained this text:

> The current year is <code>&grave;r start_year&grave;</code>.

It would render as:

> The current year is 2025.

For more help using Quarto efficiently, please see our [markdown guide](https://nmfs-ost.github.io/asar/articles/markdown_notation.html).

## How can I edit my report's alt text and captions?

Please refer to [the accessibility vignette's guide ](https://nmfs-ost.github.io/asar/articles/accessibility_guide.html#how-to-edit-your-reports-alt-text-and-captions) on editing alt text and captions.

## How can I use acronyms and edit the glossary?

Please refer to the [Acronyms and Glossary section of the accessibility vignette](https://nmfs-ost.github.io/asar/articles/accessibility_guide.html#acronyms-and-glossary) for guidance on how to use acronyms and edit the glossary.


# Tables and Figures

## Why aren't my tables and/or figures displaying on landscape-oriented pages when the landscape braces are present?

You may be using a version of Quarto [older than v1.6](https://quarto.org/docs/blog/posts/2024-11-25-1.6-release/). Please read [this Discussion post](https://github.com/nmfs-ost/asar/discussions/186) detailing how to check which version you have and update it.

## My figure and table references aren't in chronological order in the report. How do I fix this?

You will notice that the order of your figures and tables in their respective 08_tables.qmd and 09_figures.qmd docs will determine their numbers in the report. This might result in Table 2 being referenced before Table 1, for instance, in your report.

We are encouraging users to keep the order as-is for a few reasons. First, the predictability of standardized figure and table order could prove useful when comparing reports. Second, the choice of where to prioritize the figure/table order- in the Figures and Tables sections, or in the main text- is somewhat of a personal preference, rather than a hard rule. Third, as far as we know, a fix isn't yet possible with Quarto. We are choosing to focus on building other features for `asar`.

However, we understand that some will strongly prefer to set the order of their tables and figures. You *can* try manually changing the order of the figure and table chunks in the 08_tables.qmd and 09_figures.qmd docs, but this isn't a reproducible or permanent solution.

## Why are there absolute, rather than relative, filepaths for `tables_dir` and `figures_dir` at the tops of my figures and tables docs?

We tried to implement relative filepaths for these objects but decided to return to the original workflow for two reasons.

1. Hardcoding `getwd()` into the path doesn't work; when rendering your report, Quarto will recognize your "report" folder as the working directory, which probably isn't your *actual* working directory. This will result in a rendering error.

2. While hardcoding `here::here()` into the path *does* work, we recognize that some users may be unfamiliar with [the `here` package](https://here.r-lib.org/) and are not able to learn another tool while already learning `asar`. We highly recommend checking out this awesome package, but in the meantime, we are not going to force its use.

If you want to ensure `tables_dir` and `figures_dir` are relative filepaths (which may be essential if you are collaborating), you can directly edit these paths yourself and reset them using `getwd()`, `here::here()`, or some other option.

# Rendering reports

## Why am I getting the following error message when I try to render my template?

### "Missing item" error

``` error:
compilation failed- error
LaTeX Error: Something's wrong--perhaps a missing \item.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.419 \end{CSLReferences}
```

The above error message is created due to a bug introduced in Quarto in the last year where the notation in *07_references.qmd* creates an issue when there is no in-text reference in the text. To correct this, please add a temporary reference to any of the Quarto files in the outlined document (*only if you are using the default asar_references.bib file*), then replace it with real references when ready. Here is an example "temporary reference":

`Here is an example of an in-text citation (@methot_stock_2013).`

### "DocumentMetadata" error {#sec-docmetadata}

`! LaTeX Error: No support files for \DocumentMetadata found.`

The above error message occurs when LaTeX packages necessary for rendering haven't been installed.

We typically encourage users to [install the default tinytex bundle](https://github.com/nmfs-ost/asar?tab=readme-ov-file#installation) ("TinyTeX-1", installed via `tinytex::install_tinytex()`). This bundle contains most, but not all, LaTeX packages needed for rendering `asar` reports. Then, when you render your report for the first time, those missing LaTeX packages needed for rendering should install automatically (e.g., 'tagpdf'). However, this doesn't always happen; we don't know why.

Try to resolve the error by installing the full TinyTeX bundle in the R console. Since this TinyTeX bundle contains every LaTeX package you could install from CTAN ([TinyTeX-2](https://github.com/rstudio/tinytex-releases?tab=readme-ov-file#releases)), it should contain every LaTeX package needed for rendering (hence its large size):

`tinytex::install_tinytex(bundle = "TinyTeX-2")`

Then, render your report once more.

## When rendering, why does my report hang on the figures doc?

When rendering your report, it may hang when processing the figures file. If this occurs, it probably means that your TinyTeX installation isn't working properly. This may occur even if you've installed the TinyTeX bundle with every LaTeX package you could install from CTAN ([TinyTeX-2](https://github.com/rstudio/tinytex-releases?tab=readme-ov-file#releases)).

Try this: Uninstall tinytex in the R console (`tinytex::uninstall_tinytex()`), then reinstall it in the terminal (`quarto install tinytex`).

Notably, this command will install TinyTeX-1 bundle (the default), then install the necessary LaTeX packages needed for rendering *while your report is rendering the first time*. See the ["DocumentMetadata" error](#sec-docmetadata) section for more information.

## Why can't my report `find support_files/before-body.tex`?

This error can occasionally occur to some users when they are working on a remote or shared drive that does not originate from their local machine. Due to constraints of Quarto, the user must render their skeleton document when the support files and child documents are found somewhere locally.

We suggest users who encounter this problem to store their files made from `asar` on their local computer and push them to a GitHub repo to store and share.

# Adding tagging and alternative text {#sec-a11y-issues}

## When I compile my report after adding tagging or alt text, I get an error. Why?

We have experienced several seemingly random errors when developing this package. Oftentimes, these errors arise when LaTeX packages are updated and end up conflicting with one another. As a first attempt to debug, we strongly advise updating your LaTeX packages with the following command:

`tinytex::tlmgr_update()`

Close RStudio and open it again. Try again to compile your report.

If that doesn't solve your problem:

1. Reinstall your TinyTeX installation (we recommend [bundle 2](@sec-docmetadata), though bundle 1 may suffice). Update the packages and try compiling again.
2. Check out our [issues page](https://github.com/nmfs-ost/asar/issues) and [discussion board](https://github.com/nmfs-ost/asar/discussions) to see if someone else has already asked (and maybe solved!) your question.
3. If you're still struggling, [make an issue](https://github.com/nmfs-ost/asar/issues).

## I think [specific LaTeX package] is causing an issue. How do I investigate further?

If you've identified a specific LaTeX package that may be causing issues (you may be tipped off by console messages), try reinstalling the package by typing the following in the console:

`tinytex::tlmgr_install("<LaTeX package name>")`

For example, to reinstall `pdfcomment`, you'd enter `tinytex::tlmgr_install("pdfcomment")`.

Quarto *should be* installing LaTeX packages that it can't find, but sometimes it doesn't. This is a frustrating back-end issue with Quarto.

You can also verify that your package has *actually been downloaded* by typing the following:

`tinytex::tlmgr_search("<LaTeX package name>")`

# General errors

## I'm getting an error not explained in this FAQ. How do I fix it?

When getting to know `asar`, you'll probably encounter some errors. We highly recommend checking out our [issues page](https://github.com/nmfs-ost/asar/issues) and [discussion board](https://github.com/nmfs-ost/asar/discussions) to see if someone else has already asked (and maybe solved!) your question.

If you cannot find an answer, feel free to report your issue or question to the [issues page](https://github.com/nmfs-ost/asar/issues) or [discussion board](https://github.com/nmfs-ost/asar/discussions). There are multiple issue templates to choose from: request to add author affiliation, bug report, feature request, and more.
