name: Feature Request
description: Request new features or changes to features
title: "[Feature]: "
labels: ["enhancement", "triage_needed"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request! Before
        filling out this report please search the existing issues to see
        if the problem has already been reported. If it has, please add a
        comment to the open issue or link to the related, but closed, issue in
        this report.
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you would like.
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you have considered
      description: A clear and concise description of any alternative solutions or features you have considered.
      placeholder: Other solutions include ...
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
