---
title: 'Stock Assessment Report Template'
author:
  - 'FIRST LAST' 
date: today
lang: en 
cover: 
format: 
  pdf: 
    documentclass: scrartcl
    number-sections: true
    template-partials:
      - 'support_files/before-body.tex'
      - 'support_files/_titlepage.tex'
    include-in-header:
      - 'support_files/in-header.tex'
    toc: true
    lof: true
    lot: true
    titlepage-geometry: 
      - top=2in
      - bottom=1in
      - right=1in
      - left=1in
params:
   office: ''
   species: ''
   spp_latin: ''
---
{{< pagebreak >}} 

Please cite this publication as 

AUTHOR NAME. YEAR. Stock Assessment Report Template. NOAA Fisheries Science Center, CITY, STATE. 

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: '01_executive_summary'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('01_executive_summary.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: '02_introduction'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('02_introduction.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: '03_data'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('03_data.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: '04a_assessment-configuration'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('04a_assessment-configuration.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: '04b_assessment-results'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('04b_assessment-results.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: '04c_assessment-sensitivity'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('04c_assessment-sensitivity.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: '04d_asessment-benchmarks'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('04d_asessment-benchmarks.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: '04e_assessment-projections'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('04e_assessment-projections.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: '05_discussion'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('05_discussion.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: '06_acknowledgments'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('06_acknowledgments.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: '07_references'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('07_references.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: '08_tables'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('08_tables.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: '09_figures'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('09_figures.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: '10_notes'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('10_notes.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: '11_appendix'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('11_appendix.qmd', quiet = TRUE)
cat(a, sep = '\n')
```
