# Executive Summary {#sec-exec-sum}

<!--- Where possible, the executive summary should paraphrase the shared content of the body of the report to minimize redundancy.--->

## Stock {#sec-stock .unnumbered}


## Catches {#sec-catches .unnumbered}


## Data and assessment {#sec-data-and-assessment .unnumbered}


## Stock biomass and dynamics {#sec-stock-biomass-and-dynamics .unnumbered}


## Recruitment {#sec-recruitment .unnumbered}


## Exploitation status {#sec-exploitation-status .unnumbered}


## Ecosystem considerations {#sec-ecosystem-considerations .unnumbered}


## Reference points {#sec-reference-points .unnumbered}


## Management performance {#sec-management-performance .unnumbered}


## Unresolved problems and major uncertainties {#sec-unresolved-problems-and-major-uncertainties .unnumbered}


## Decision table and projections {#sec-decision-table-and-projections .unnumbered}


## Scientific uncertainty {#sec-scientific-uncertainty .unnumbered}


## Research and data needs {#sec-research-and-data-needs .unnumbered}
