#' Export key quantities to SIS via Google Drive
#'
#' Submit completed stock assessment data to SIS via a Google Drive folder.
#' 
#' @param sis_data_dir Location of the sis_assmt_template.csv and sis_ts_template.csv files.
#' 
#' Default: The working directory.
#' 
#'  
#' @details This function acts within the following workflow:
#' 
#' 1. When a stock assessment is scheduled to conclude, SIS will generate an
#'  attachment or prompt containing metadata and identifiers.
#' 2. The user will open two csv files containing placeholders for all of the data required by SIS: sis_assmt_template.csv (assessment summary data) and sis_ts_template.csv (time series data). There are three ways to obtain these files:
#' 2a. Generate the files by running `asar::create_blank_sis()`
#' 2b. Locate the files in the "report" folder generated by running `asar::create_template()`.
#' 2c. Run `stockplotr::extract_sis_data()`, which will populate the templates with data originating from a converted model results file.
#' 3. The user will add the remaining necessary data into the csv files, ensuring that all required fields are completed.
#' 4. Run `export_to_sis()`, which will format and upload this data to a specific Google Drive folder.
#' 5. The uploaded contents will be resubmitted to SIS to finalize the record.
#' 
#' @export
#'
#' @examples
#' \dontrun{
#' export_to_sis(
#'   sis_data_dir = getwd()
#' )
#' }
#'
export_to_sis <- function(
    sis_data_dir = getwd()
){
  # Read in, clean, check, format assessment data
  sis_assmt_data <- read.csv(file.path(sis_data_dir, "sis_assmt_template.csv"), stringsAsFactors = FALSE) |>
    dplyr::select(-Explanation, -Default)
  
  # check data for required fields and character limits
  if (nchar(sis_assmt_data$Value[sis_assmt_data$Argument == "AS_B_COMMENT"]) > 1000){
    stop("AS_B_COMMENT exceeds 1,000 character limit")
  }

  if (nchar(sis_assmt_data$Value[sis_assmt_data$Argument == "AS_F_COMMENT"]) > 1000){
    stop("AS_F_COMMENT exceeds 1,000 character limit")
  }

  required_missing <- sis_assmt_data |>
    dplyr::filter(Optional == "NO") |>
    dplyr::filter(Value == "") 
  
  missing_vars <- length(required_missing$Argument)
  if (missing_vars > 0){
    cli::cli_bullets(c(
      "x" = "Missing {missing_vars} required field{?s}:",
      stats::setNames(as.character(required_missing$Argument), rep("*", missing_vars))
    ))
    stop("Please provide values for the missing required fields in sis_data.csv, then rerun the function.")
  }
  
  # add empty fields for SIS to fill in
  null_fields <- data.frame(
    Argument = c(
      "DATE_CREATED",
      "CREATED_BY",
      "DATE_MODIFIED",
      "MODIFIED_BY",
      "AS_LOCKED_FLAG",
      "AS_LEAD_LAB",
      "AS_TIMESERIES_LOCKED_FLAG",
      "AS_SURVEY_LINK_LOCKED_FLAG",
      "AS_FISCAL_YEAR",
      "AS_LOCKED_FLAG_BY",
      "AS_LOCKED_FLAG_DATE",
      "AS_TIMESERIES_LOCKED_FLAG_BY",
      "AS_TIMESERIES_LOCKED_FLAG_DATE",
      "AS_SURVEY_LINK_LOCKED_FLAG_BY",
      "AS_SURVEY_LINK_LOCKED_FLAG_DATE",
      "PLANNED_ASSESSMENT_ID",
      "ENT_ID",
      "ENT_NAME",
      "ATS_CNT",
      "ASL_CNT"
    ),
    Value = c(rep("", 20)))
  
  sis_assmt_data <- sis_assmt_data |>
    dplyr::select(-Optional) |>
    dplyr::mutate(Value = as.character(Value)) |>
    dplyr::full_join(null_fields, by = c("Argument", "Value"))
  
  
  # read in, clean, check, format time series data
  sis_ts_data <- read.csv(file.path(sis_data_dir, "sis_ts_template.csv"), stringsAsFactors = FALSE)
  
  if (!exists(sis_ts_data$Year)){
    cli::cli_abort("sis_ts_template.csv is missing the 'Year' column. This column is mandatory.")
  }
  
  primary_type <- sis_ts_data |>
    dplyr::filter(Primary == "Y") |>
    dplyr::pull(Category)
  
  if (length(primary_type) > 1) {
    cli::cli_abort("Multiple categories are marked as 'Y' in the 'Primary' column. Only one category can be designated as 'Y'.")
  } else if (length(primary_type) == 0) {
    cli::cli_abort("Zero categories are marked as 'Y' in the 'Primary' column. One category ('Spawners' or 'Biomass') must be designated as 'Y'.")
  } else {
    if (primary_type %notin% c("Spawners", "Biomass")){
      cli::cli_abort("Neither 'Spawners' nor 'Biomass' categories marked as 'Y'. One of these categories must be designated as 'Y'.")
    }
  }


  # name json file
  assess_ID <- sis_assmt_data |>
    dplyr::filter(Argument == "ASSESSMENT_ID") |>
    dplyr::pull(Value)
  
  entity_ID <- sis_assmt_data |>
    dplyr::filter(Argument == "ENTITY_ID") |>
    dplyr::pull(Value)
  
  model_identifier <- sis_assmt_data |>
    dplyr::filter(Argument == "MODEL_IDENTIFIER") |>
    dplyr::pull(Value)
  
  if (length(model_identifier) == 0 || is.na(model_identifier) || model_identifier == "") {
    model_identifier <- NA
  }
  
  # final filename
  filename <- paste0(assess_ID, "_", entity_ID, ifelse(is.na(model_identifier), "", paste0("_", model_identifier))) |>
    # Replace non-alphanumeric/hyphen/underscore characters with "_"
    stringr::str_replace_all("[^a-zA-Z0-9_-]", "_") |>
    # Collapse consecutive underscores into one
    stringr::str_replace_all("_+", "_") |>
    # Trim underscores from the beginning and end
    stringr::str_remove("^_+|_+$") |>
    paste0(".json")
  
  
  # prep datasets for conversion into json
  sis_list <- setNames(as.list(sis_assmt_data$Value), sis_assmt_data$Argument)
  
  categories <- sis_ts_data |>
    dplyr::filter(Primary == "Y") |>
    dplyr::pull(Category)
  
  nested_list <- list(
    SUMMARY = sis_list,
    TIMESERIES = list(
      PARAMETERS = list(
        TSC_NAME = categories
      ),
      DATA = ts_data_matrix
    )
    # SUMMARY = as.list(sis_list[1, ]),
  )
  
  
  # write json file
  jsonlite::write_json(
    x = sis_list, 
    path = fs::path(getwd(), filename), 
    pretty = TRUE,       # Formats the JSON with clean indentation
    auto_unbox = TRUE    # Ensures single values don't convert to JSON arrays ([13879])
  )
  
  # TODO: Make breakpoint to let author decide if json file is accurate and ready to upload to Google Drive
  
  #TODO: create pipeline to upload to Google Drive via API once created
  googledrive::drive_upload(
    media = fs::path(getwd(), filename),
    # TODO: replace drive folder link with NMFS agency wide folder for depositing json files for Jeff
    path = "https://drive.google.com/drive/folders/1eZ_2Y38ftFffr2-EhC30ia1N_4Igacvg?usp=drive_link/",
    name = filename,
    overwrite = TRUE # Do we want to overwrite?
  )
}
