#' Export key quantities to SIS via Google Drive
#'
#' Submit completed stock assessment data to SIS via a Google Drive folder.
#' 
#' @param sis_data_dir Location of the sis_data_template.csv file.
#' 
#' Default: The working directory.
#' 
#'  
#' @details This function acts within the following workflow:
#' 
#' 1. When a stock assessment is scheduled to conclude, SIS will generate an
#'  attachment or prompt containing metadata and identifiers.
#' 2. The user will open a csv file containing placeholders for all of the data required by SIS ("sis_data_template.csv"). There are three ways to obtain this file:
#' 2a. Generate the file by running `asar::create_blank_sis()`
#' 2b. Locate the file in the "report" folder generated by running `asar::create_template()`,
#' 2c. Run `stockplotr::extract_sis_data()`, which will populate the blank template with data originating from a converted model results file.
#' 3. The user will add the necessary data into the csv file, ensuring that all required fields are completed.
#' 4. Run `export_to_sis()`, which will format and upload this data to a specific Google Drive folder.
#' 5. The uploaded contents will be resubmitted to SIS to finalize the record.
#' 
#' @export
#'
#' @examples
#' \dontrun{
#' export_to_sis(
#'   sis_data_dir = getwd()
#' )
#' }
#'
export_to_sis <- function(
    sis_data_dir = getwd()
){
  
  sis_data <- read.csv(file.path(sis_data_dir, "sis_data_template.csv"), stringsAsFactors = FALSE) |>
    dplyr::select(-Explanation, -Default)
  
  if (nchar(sis_data$Value[sis_data$Argument == "AS_B_COMMENT"]) > 1000){
    stop("AS_B_COMMENT exceeds 1,000 character limit")
  }

  if (nchar(sis_data$Value[sis_data$Argument == "AS_F_COMMENT"]) > 1000){
    stop("AS_F_COMMENT exceeds 1,000 character limit")
  }

  required_missing <- sis_data |>
    dplyr::filter(Optional == "NO") |>
    dplyr::filter(Value == "") 
  
  missing_vars <- length(required_missing$Argument)
  if (missing_vars > 0){
    cli::cli_bullets(c(
      "x" = "Missing {missing_vars} required field{?s}:",
      stats::setNames(as.character(required_missing$Argument), rep("*", missing_vars))
    ))
    stop("Please provide values for the missing required fields in sis_data.csv, then rerun the function.")
  }
  
  null_fields <- data.frame(
    Argument = c(
      "DATE_CREATED",
      "CREATED_BY",
      "DATE_MODIFIED",
      "MODIFIED_BY",
      "AS_LOCKED_FLAG",
      "AS_LEAD_LAB",
      "AS_TIMESERIES_LOCKED_FLAG",
      "AS_SURVEY_LINK_LOCKED_FLAG",
      "AS_FISCAL_YEAR",
      "AS_LOCKED_FLAG_BY",
      "AS_LOCKED_FLAG_DATE",
      "AS_TIMESERIES_LOCKED_FLAG_BY",
      "AS_TIMESERIES_LOCKED_FLAG_DATE",
      "AS_SURVEY_LINK_LOCKED_FLAG_BY",
      "AS_SURVEY_LINK_LOCKED_FLAG_DATE",
      "PLANNED_ASSESSMENT_ID",
      "ENT_ID",
      "ENT_NAME",
      "ATS_CNT",
      "ASL_CNT"
    ),
    Value = c(rep("", 20)))
  
  sis_data <- sis_data |>
    dplyr::select(-Optional) |>
    dplyr::mutate(Value = as.character(Value)) |>
    dplyr::full_join(null_fields, by = c("Argument", "Value"))
                  
  # left off here
  # TIME_SERIES <- data.frame(
  #   Year = c(2000, 2001, 2002),
  #   Catch_Metric_Tons = c(1000, 1100, 1200),
  #   Spawners_Metric_Tons = c(5000, 5500, 6000),
  #   Recruitment_Recruits_Age_1 = c(10000, 11000, 12000),
  #   Fmort_Fully_selected_F = c(0.1, 0.15, 0.2)
  # )
  
  # time_series <- TIME_SERIES |>
  #   tidyr::pivot_longer(cols = -Year, names_to = "Metric", values_to = "Value") |>
  #   tidyr::unite("Metric_Unit", Metric, sep = "_") |>
  #   tidyr::pivot_wider(names_from = Metric_Unit, values_from = Value)
  
  sis_list <- setNames(as.list(sis_data$Value), sis_data$Argument)
  
  # final filename
  filename <- paste0(ASSESSMENT_ID, "_", ENTITY_ID, "_", model_identifier)  |>
    # Replace non-alphanumeric/hyphen/underscore characters with "_"
    stringr::str_replace_all("[^a-zA-Z0-9_-]", "_") |>
    # Collapse consecutive underscores into one
    stringr::str_replace_all("_+", "_") |>
    # Trim underscores from the beginning and end
    stringr::str_remove("^_+|_+$") |>
    paste0(".json")
  
  jsonlite::write_json(
    x = sis_list, 
    path = fs::path(getwd(), filename), 
    pretty = TRUE,       # Formats the JSON with clean indentation
    auto_unbox = TRUE    # Ensures single values don't convert to JSON arrays ([13879])
  )
  
  #TODO: create pipeline to upload to Google Drive via API once created
  googledrive::drive_upload(
    media = fs::path(getwd(), filename),
    # TODO: replace drive folder link with NMFS agency wide folder for depositing json files for Jeff
    path = "https://drive.google.com/drive/folders/1eZ_2Y38ftFffr2-EhC30ia1N_4Igacvg?usp=drive_link/",
    name = filename,
    overwrite = TRUE # Do we want to overwrite?
  )
}
