# Checks that the pkgdown site builds for a repository.
# this assumes pkgdown is already set up.
name: call-build-pkgdown
# on specifies the build triggers. See more info at https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
# this workflow runs on pushes to main or master or any time a new tag is pushed
# it also runs everytime a pull request to main or master is opened.
  push:
    branches: [main, master]
    tags: ['*']
  pull_request:
    branches: [main, master]
    
# no permissions are needed by the default github token for this workflow to 
# run, so don't pass any.
# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
permissions: {}

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v6
        
      - name: run additional args on windows
        if: matrix.config.os == 'windows-latest'
        run: ${{ inputs.additional_args_windows }}
      
      - name: run additional args on macOS
        if: matrix.config.os == 'macOS-latest'
        run: ${{ inputs.additional_args_macos }}
        
      - name: run additional args on ubuntu
        if: matrix.config.os == 'ubuntu-latest'
        run: ${{ inputs.additional_args_ubuntu }}

      - uses: r-lib/actions/setup-pandoc@v2
            
      - name: Set up Quarto 
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install TinyTeX
        run: quarto install tool tinytex
        
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::., any::quarto, nmfs-ost/stockplotr
          needs: website

      - name: build pkgdown
        run: |
          Rscript -e 'pkgdown::build_site()'
     
      - name: save pkgdown output
        uses: actions/upload-artifact@v7
        with:
          name: pkgdown-site
          path: docs/
