# Automatically adds a comment containing a reviewer checklist
name: new-version-checklist
on:
  schedule:
    - cron: '0 0 28 * *'  # Runs at 00:00 on the 28th day of every month
  workflow_dispatch:     
jobs:
  new-version-checklist:
    runs-on: ubuntu-latest
    name: new-version-checklist
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: monthly release checklist"
          title: "Release Checklist - Monthly Update"
          branch: "release-checklist/monthly"
          delete-branch: true
          body: |
            # New (monthly) version checklist

            - [ ] Package version in DESCRIPTION has been updated
            - [ ] Release notes have been drafted/published
            - [ ] Cheatsheet content has been updated (if applicable)
            - [ ] Cheatsheet version has been updated (if applicable)
