# This workflow automatically adds a comment containing a reviewer checklist
# when a new pull request is opened.
name: Add a comment with reviewer checklist when PR opened
on:
  pull_request:
    types: [opened]
jobs:
  pr-checklist:
    runs-on: ubuntu-latest
    name: pr-checklist
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Comment PR'
        uses: actions/github-script@0.3.0
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            var msg = `# Checklist

            - [ ] PR base branch is accurate
            - [ ] Is the code concise?
            - [ ] Comments are clear and useful.
            - [ ] Can you remove or combine any arguments?
            - [ ] Do argument contain defaults (if appliable)?
            - [ ] Code is documented and example provided (Roxygen).
            - [ ] Did you make a test (testthat)?
            - [ ] Was this tested under multiple scenarios?
            - [ ] Did you run devtools::check()?
            
            `
            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
            github.issues.createComment({ issue_number, owner, repo, body: msg });
